# This code is generated by DeepSeek engine.
# The code is modified by Dr Irfan Azhar on 06 Dec 2025 to compute single digit values.


import csv
from utils import summingMethod


def calculate_cumulative_sum(input_file, output_file):
    """
    Reads a CSV file, calculates cumulative sum for 'arabic-letter-weight' column,
    and writes the result to a new CSV file.

    Args:
        input_file (str): Path to input CSV file
        output_file (str): Path to output CSV file
    """

    # Read the input CSV file
    with open(input_file, 'r', newline='') as infile:
        reader = csv.DictReader(infile)

        # Get the fieldnames (column headers)
        fieldnames = reader.fieldnames

        # Store all rows
        rows = []
        for row in reader:
            rows.append(row)

    # Calculate cumulative sum for arabic-letter-weight
    cumulative_total = 0

    for row in rows:
        # Convert arabic-letter-weight to integer
        current_value = int(row['arabic-chapter-weight'])

        # Add to cumulative total
        cumulative_total += current_value

        # Update the row with cumulative value
        row['arabic-chapter-weight'] = str(cumulative_total)

    # Write to output CSV file
    with open(output_file, 'w', newline='') as outfile:
        writer = csv.DictWriter(outfile, fieldnames=fieldnames)

        # Write header
        writer.writeheader()

        # Write all rows with cumulative sums
        writer.writerows(rows)

    print(f"Successfully created cumulative sum file: {output_file}")
    print(f"Processed {len(rows)} rows")


# Alternative version using pandas (simpler if you have pandas installed)
def compute_one_digit_cumulative_sum(input_file, output_file):
    """
    An arrangement to compute one-digit-cummulative sum
   Reads a CSV file, calculates cumulative sum for 'arabic-letter-weight' column,
    and writes the result to a new CSV file.

    Args:
        input_file (str): Path to input CSV file
        output_file (str): Path to output CSV file
    """

    # Read the input CSV file
    with open(input_file, 'r', newline='') as infile:
        reader = csv.DictReader(infile)

        # Get the fieldnames (column headers)
        fieldnames = reader.fieldnames

        # Store all rows
        rows = []
        for row in reader:
            rows.append(row)

    # Calculate cumulative sum for arabic-letter-weight
    cumulative_total = 0

    for row in rows:
        # Convert arabic-letter-weight to integer
        current_value = int(row['arabic-chapter-weight'])

        # Add to cumulative total
        cumulative_total += current_value
        if cumulative_total > 9:
            tempInt = cumulative_total
            cumulative_total = summingMethod (tempInt)

        # Update the row with cumulative value
        row['arabic-chapter-weight'] = str(cumulative_total)

    # Write to output CSV file
    with open(output_file, 'w', newline='') as outfile:
        writer = csv.DictWriter(outfile, fieldnames=fieldnames)

        # Write header
        writer.writeheader()

        # Write all rows with cumulative sums
        writer.writerows(rows)

    print(f"Successfully created cumulative sum file: {output_file}")
    print(f"Processed {len(rows)} rows")


if __name__ == "__main__":
    # Input and output file paths
    input_csv = "dictQM_SS_03_Dec_2025.csv"
    output_csv = "cummulative_sum_SS_06_Dec_2025.csv"

    # Choose which method to use:
    # Method 1: Using standard csv module (no external dependencies)
    calculate_cumulative_sum(input_csv, output_csv)


    # Optional: Print the result for verification
    print("\nVerification - First few rows of output with simple cumulative sum:")
    with open(output_csv, 'r', newline='') as f:
        reader = csv.reader(f)
        for i, row in enumerate(reader):
            if i < 8:  # Print first 8 rows (header + 7 data rows)
                print(row)
            else:
                break

    # in the following section we recompute the cummulative sum whereby whenever the cummulative sum is greater than 9
    # which means it goes to two-difit format like 10 and above, then we invoke a method to sum those two digits and
    # the resultant cum-sum of one-digit number is recorded.

    input_csv = "dictQM_SS_03_Dec_2025.csv"
    output_csv = "cummulative_sum_SS_each_row_reduced_to_one_digit_06_Dec_2025.csv"

    compute_one_digit_cumulative_sum(input_csv, output_csv)

    print("\nVerification - First few rows of output with each row sum reduced to one digit only:")
    with open(output_csv, 'r', newline='') as f:
        reader = csv.reader(f)
        for i, row in enumerate(reader):
            if i < 20:  # Print first 8 rows (header + 7 data rows)
                print(row)
            else:
                break