# This code is generated by DeepSeek engine. We use the method "generate_custom_fibonacci" for our computations.
# The code is modified by Dr Irfan Azhar on 06 Dec 2025 to compute single digit values.
# This machine could not generate Fib sequence when the length of interim Fib number exceeded 4300 digit.
# We halted the operation. Computed single=-digit-weight files for dicTQM_LL (letters) and then re-ran the script.

import csv
from utils import summingMethod


# Alternative: Using original values as seeds for Fibonacci
def generate_custom_fibonacci_plain(weightFlag, input_file, output_file):
    """
    Uses first two values from CSV as seeds, then generates Fibonacci sequence.
    Example: If first values are 2 and 60, sequence becomes: 2, 60, 62, 122, 184...
    """

    # Read the input CSV file
    with open(input_file, 'r', newline='') as infile:
        reader = csv.DictReader(infile)

        # Get the fieldnames (column headers)
        fieldnames = reader.fieldnames

        # Store all rows
        rows = []
        for row in reader:
            rows.append(row)

    if len(rows) >= 2:
        # Get first two values as seeds
        seed1 = int(rows[0][weightFlag])
        seed2 = int(rows[1][weightFlag])

        # Generate custom Fibonacci sequence
        fibonacci_seq = [seed1, seed2]
        count = 0
        for i in range(2, len(rows)):
            next_val = fibonacci_seq[i - 1] + fibonacci_seq[i - 2]
            print(f'the {count}th Fibonacci sum is  {next_val}')
            count = count + 1
            #if count == 20:
            #    exit(1)
            fibonacci_seq.append(next_val)

            # Update the row
            rows[i][weightFlag] = (next_val)

        # Update first two rows (keeping original values)
        rows[0][weightFlag] = str(seed1)
        rows[1][weightFlag] = str(seed2)

    # Write to output CSV file
    with open(output_file, 'w', newline='') as outfile:
        writer = csv.DictWriter(outfile, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"Successfully created custom Fibonacci file with plain Fibonacci values: {output_file}")
    return rows

def generate_custom_fibonacci_single_digit (weightFlag, input_file, output_file):
    """
        Uses first two values from CSV as seeds, then generates Fibonacci sequence.
        Example: If first values are 2 and 60, sequence becomes: 2, 60, 62, 122, 184...
        """

    # Read the input CSV file
    with open(input_file, 'r', newline='') as infile:
        reader = csv.DictReader(infile)

        # Get the fieldnames (column headers)
        fieldnames = reader.fieldnames

        # Store all rows
        rows = []
        for row in reader:
            rows.append(row)

    if len(rows) >= 2:
        # Get first two values as seeds
        seed1 = int(rows[0][weightFlag])
        seed2 = int(rows[1][weightFlag])

        # Generate custom Fibonacci sequence
        fibonacci_seq = [seed1, seed2]

        for i in range(2, len(rows)):
            next_val = fibonacci_seq[i - 1] + fibonacci_seq[i - 2]
            if next_val > 9:
                tempInt = next_val
                next_val = summingMethod(tempInt)
            fibonacci_seq.append(next_val)

            # Update the row
            rows[i][weightFlag] = (next_val)

        # Update first two rows (keeping original values)
        rows[0][weightFlag] = str(seed1)
        rows[1][weightFlag] = str(seed2)

    if seed1 > 9:
        tempInt = seed1
        rows[0][weightFlag] = summingMethod(tempInt)

    if seed2 > 9:
        tempInt1 = seed2
        rows[0][weightFlag] = summingMethod(tempInt1)


    # Write to output CSV file
    with open(output_file, 'w', newline='') as outfile:
        writer = csv.DictWriter(outfile, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"Successfully created custom Fibonacci file with single digit numbers: {output_file}")
    return rows

def print_comparison(original_file, fibonacci_file):
    """Print comparison between original and Fibonacci sequence."""

    print("\n" + "=" * 60)
    print("COMPARISON: Original vs Fibonacci Sequence")
    print("=" * 60)

    # Read original
    with open(original_file, 'r', newline='') as f:
        original = list(csv.reader(f))

    # Read Fibonacci
    with open(fibonacci_file, 'r', newline='') as f:
        fibonacci = list(csv.reader(f))

    print(f"{'Row':<4} {'Original':<15} {'Fibonacci':<15} {'Difference':<15}")
    print("-" * 60)

    for i in range(1, min(len(original), len(fibonacci))):
        orig_val = int(original[i][1])  # 5th column (index 4)
        fib_val = int(fibonacci[i][1])
        diff = fib_val - orig_val

        print(f"{i:<4} {orig_val:<15} {fib_val:<15} {diff:<15}")


if __name__ == "__main__":
    # the following commented-out block does not run properly since at certain sequnce number, length of the Fib value exceeds
    # 4300 digits which is normally allowed by the OS. Therefore, we did not modify the system paramters, and instead of that,
    # we summed up each value of the Fib seq to single digit.

    """
    # Input and output file paths
    weightField = 'arabic-word-weight'
    input_csv = "dictQM_WW_single_digit_06_Dec_2025.csv"
    output_csv = "fibonacci_sequence_WW_plain_06_Dec_2025.csv"

    # Choose which Fibonacci method to use:
    print("Generating Fibonacci sequence...")

    # Method 1: Fibonacci-like using first two values as given
    # (If first two values are 2 and 60, sequence: 2, 60, 62, 122, 184...)
    rows = generate_custom_fibonacci_plain(weightField, input_csv, output_csv)

    # Print verification
    print("\nVerification - First few rows of Fibonacci output:")
    with open(output_csv, 'r', newline='') as f:
        reader = csv.reader(f)
        for i, row in enumerate(reader):
            if i < 8:  # Print first 8 rows
                print(row)
            else:
                break

    # Show comparison
    print_comparison(input_csv, output_csv)
    """
    weightField = 'arabic-chapter-weight'
    input_csv = "dictQM_SS_single_digit_06_Dec_2025.csv"
    output_csv = "fibonacci_sequence_SS_single_digit_06_Dec_2025.csv"
    rows = generate_custom_fibonacci_single_digit(weightField, input_csv, output_csv)

    # Show comparison
    print_comparison(input_csv, output_csv)

